### ISSUE TITLE
error open dir

### ISSUE THREAD

**Issue by delta4d** [delta4d/atree.js#3]
```
atree I_dont_exist
```

```
const file = opts._.length == 0 ? "." : opts[_][0];

ReferenceError: _ is not defined
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v7.9.0/lib/node_modules/atree/cli.js:89:47)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by delta4d** [comment]
Duplicate of #7

**Comment by delta4d** [comment]
It seems easy to forgot what I have down after 6 months...

that is life...
